name: Build and Run Docker

on:
  push:
    branches:
      - main  # or master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t my-first-dock .

    - name: Run Docker container
      run: docker run my-first-dock
      
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Convert repository owner to lowercase
      id: lower
      run: echo "owner_lower=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
    
    - name: Tag Docker image
      run: docker tag my-first-dock ghcr.io/${{ env.owner_lower }}/my-first-dock:latest
    
    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ env.owner_lower }}/my-first-dock:latest

